# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', null=True, upload_to='pic_folder/'),
        ),
    ]
