# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='pic_folder/'),
        ),
    ]
